### ISSUE TITLE
할일을 등록해 주세요

### ISSUE THREAD

**Issue by mocona** [ProjectInTheClass/HiMoveIt#12]
팀원들 별로, 할당받은 업무를 이곳에 등록해 주세요.

할당도 잊지 말고.

일이 큰 덩어리라면, 등록 후 그 일을 쪼개서 추가로 등록하면 됩니다.

최대 시간단위로 쪼개면 좋지만, 일자별로 (최대 2일 정도까지를 잡고) 할 일을 나누세요~

**Comment by KangKyung** [comment]
작성 완료
